base setup carousel
DaanKorver/cmd-midterm-components pull request #16
Opened 2022-11-16 12:11 UTC by NBadeloe

2022-11-17 11:20 UTC, boudewijnbout requested changes

2022-11-17 11:20 UTC, boudewijnbout commented on src/lib/components/Carousel.svelte
> +    <section class="carousel">
Try to avoid using classes. And start using scoped CSS in SvelteKit. Way easier and makes your code more clean.

2022-11-17 11:20 UTC, boudewijnbout commented on src/routes/+page.svelte
> +<Carousel></Carousel>
Use a single line here like: <Carousel />

2022-11-17 15:31 UTC, DaanKorver commented on src/routes/+page.svelte
> +<Carousel></Carousel>
```<Carousel/>```

2022-11-18 11:08 UTC, boudewijnbout approved these changes
LGTM!

2022-11-18 11:23 UTC, merged