eature/footer
DaanKorver/cmd-midterm-components pull request #18
Opened 2022-11-16 14:41 UTC by M4TThys123

2022-11-17 11:18 UTC, boudewijnbout requested changes

2022-11-17 11:18 UTC, boudewijnbout commented on src/lib/components/footer.svelte
> +			padding: 1rem 5rem;
Did you check that the padding is the same on for example the header?

2022-11-17 15:08 UTC, DaanKorver requested changes

2022-11-17 15:08 UTC, DaanKorver commented on src/lib/components/footer.svelte
> +	<span>© 2022 CMD AMSTERDAM</span>
En ```<slot/>``` gebruiker aub

2022-11-18 01:50 UTC, M4TThys123 commented on src/lib/components/footer.svelte
> +			padding: 1rem 5rem;
I'm changing it to:
```css
@media (max-width: 45rem) { 
}
```

2022-11-18 11:27 UTC, boudewijnbout approved these changes
LGTM!

2022-11-18 11:38 UTC, DaanKorver approved these changes

2022-11-18 11:38 UTC, merged